# This is a basic workflow to help you get started with Actions

name: Salesforce CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use nvm to install and use Node.js
        run: |
          . ~/.nvm/nvm.sh
          nvm install 18.20.4
          nvm use 18.20.4
          node --version

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli
          sfdx -v

      - name: Authenticate with Salesforce
        run: sfdx auth:sfdxurl:store -f sfdx-url.txt

      - name: Static Code Analysis
        run: |
          cd MyProject
          sfdx force:source:convert -d mdapi
          sfdx scanner:run --target ./mdapi --format table

      # - name: Deploy to Salesforce
      #   run: |
      #     sfdx force:source:deploy -p force-app -u MySandbox



